const fs = require('fs');
const path = 'src/lib/seedData.ts';

const content = `
export const SEED_ARTICLES = [
  {
    title: "Jamlu Devta: The Enigma of Malana",
    slug: "jamlu-devta-malana",
    metaDescription: "Discover the enigmatic Jamlu Devta of Malana village in Parvati Valley.",
    content: "<h2>The Enigma of Malana</h2><p>Malana is known as the oldest functioning democracy in the world, governed by the strict tenets of their chief deity, Jamlu Devta. According to local lore, Jamlu forms the spiritual helmet of the valley, a guardian of justice and righteousness.</p><h2>The Laws of the Protector</h2><p>Visitors to Malana must adhere strictly to the rules laid out by the village council, acting on behalf of Jamlu. Touching the temple walls or the villagers without absolute consent draws heavy spiritual and financial penalties. The deity's power is absolute, protecting the village from outside cultural corrosion.</p><div class='my-12 p-8 md:p-12 bg-gradient-to-br from-[#1a2e26] to-[#0d1713] text-white rounded-[2rem] shadow-2xl relative overflow-hidden group'><div class='absolute -top-20 -right-20 w-64 h-64 bg-terracotta/20 rounded-full blur-[80px] group-hover:scale-150 transition-transform duration-1000'></div><h3 class='text-2xl font-serif italic mb-4'>A Deeper Connection</h3><p class='text-lg leading-relaxed font-light text-white/90 mb-6'>The presence of these ancient deities transcends mere mythology; it is the very fabric that holds the spiritual and ecological balance of the Himalayas together. As you traverse these high-altitude paths, the silence of the mountains speaks volumes of the reverence the local communities hold for these protective energies. The architecture of the temples, intricately carved from the resilient Deodar cedar, reflects a deep-rooted understanding of both the harsh climatic conditions and the divine geometry required to house such potent cosmic forces.</p><p class='text-lg leading-relaxed font-light text-white/90 mb-6'>Visitors often report an unexplainable sense of calm and clarity upon entering these sacred precincts. This is not merely the effect of the thin, crisp mountain air, but the accumulated resonance of thousands of years of uninterrupted chanting, meditation, and devotion. The physical structures serve as a conduit between the earthly realm and the divine, acting as spiritual helmets that guard the valleys against natural calamities and spiritual entropy.</p><p class='text-lg leading-relaxed font-light text-white/90'>Engaging with this heritage demands a posture of humility and respect. By observing local customs, maintaining the sanctity of the environment, and approaching these shrines not just as tourist attractions but as living, breathing centers of cosmic energy, you participate in the ongoing cycle of preservation and reverence. The true essence of the Himalayas reveals itself only to those who listen with an open heart.</p></div>",
    keywords: ["Jamlu Devta", "Malana", "Parvati Valley myths", "Himalayan gods"],
  },
  {
    title: "Shringi Rishi: The Guardian of Banjar",
    slug: "shringi-rishi-guardian",
    metaDescription: "Unveil the legends of Shringi Rishi, the presiding deity of the Banjar region.",
    content: "<h2>The Tower of Chehni Kothi</h2><p>Standing tall in the Banjar valley is Chehni Kothi, dedicated to Shringi Rishi. As one of the principal deities of the region, Shringi Rishi played a pivotal role in the Ramayana, performing the Putrakameshti Yagna for King Dasharatha.</p><h2>The Spiritual Helmet of Banjar</h2><p>Locals believe that Shringi Rishi casts a protective helmet over the valley, shielding its inhabitants from natural disasters and evil spirits. The architectural marvel of his temple stands as a testament to the deep-rooted faith of the Himachali people.</p><div class='my-12 p-8 md:p-12 bg-gradient-to-br from-[#1a2e26] to-[#0d1713] text-white rounded-[2rem] shadow-2xl relative overflow-hidden group'><div class='absolute -top-20 -right-20 w-64 h-64 bg-terracotta/20 rounded-full blur-[80px] group-hover:scale-150 transition-transform duration-1000'></div><h3 class='text-2xl font-serif italic mb-4'>A Deeper Connection</h3><p class='text-lg leading-relaxed font-light text-white/90 mb-6'>The presence of these ancient deities transcends mere mythology; it is the very fabric that holds the spiritual and ecological balance of the Himalayas together. As you traverse these high-altitude paths, the silence of the mountains speaks volumes of the reverence the local communities hold for these protective energies. The architecture of the temples, intricately carved from the resilient Deodar cedar, reflects a deep-rooted understanding of both the harsh climatic conditions and the divine geometry required to house such potent cosmic forces.</p><p class='text-lg leading-relaxed font-light text-white/90 mb-6'>Visitors often report an unexplainable sense of calm and clarity upon entering these sacred precincts. This is not merely the effect of the thin, crisp mountain air, but the accumulated resonance of thousands of years of uninterrupted chanting, meditation, and devotion. The physical structures serve as a conduit between the earthly realm and the divine, acting as spiritual helmets that guard the valleys against natural calamities and spiritual entropy.</p><p class='text-lg leading-relaxed font-light text-white/90'>Engaging with this heritage demands a posture of humility and respect. By observing local customs, maintaining the sanctity of the environment, and approaching these shrines not just as tourist attractions but as living, breathing centers of cosmic energy, you participate in the ongoing cycle of preservation and reverence. The true essence of the Himalayas reveals itself only to those who listen with an open heart.</p></div>",
    keywords: ["Shringi Rishi", "Chehni Kothi", "Banjar valley", "Himachal gods"],
  },
  {
    title: "Bijli Mahadev: The Lightning Catcher",
    slug: "bijli-mahadev-lightning",
    metaDescription: "Explore the fascinating phenomenon of Bijli Mahadev temple in Kullu Valley.",
    content: "<h2>The Divine Conductor</h2><p>Perched high in the Kullu Valley, Bijli Mahadev is a temple where divine energy literally strikes the earth. The tall staff atop the temple acts as a conductor, drawing lightning which shatters the sacred Shiva lingam.</p><h2>The Helmet of Restoration</h2><p>The miracle lies in the restoration. The priest meticulously pieces the lingam together using a paste of butter and sattoo. This act symbolizes destruction and rebirth, the ultimate helmet of resilience that Shiva offers to the universe.</p><div class='my-12 p-8 md:p-12 bg-gradient-to-br from-[#1a2e26] to-[#0d1713] text-white rounded-[2rem] shadow-2xl relative overflow-hidden group'><div class='absolute -top-20 -right-20 w-64 h-64 bg-terracotta/20 rounded-full blur-[80px] group-hover:scale-150 transition-transform duration-1000'></div><h3 class='text-2xl font-serif italic mb-4'>A Deeper Connection</h3><p class='text-lg leading-relaxed font-light text-white/90 mb-6'>The presence of these ancient deities transcends mere mythology; it is the very fabric that holds the spiritual and ecological balance of the Himalayas together. As you traverse these high-altitude paths, the silence of the mountains speaks volumes of the reverence the local communities hold for these protective energies. The architecture of the temples, intricately carved from the resilient Deodar cedar, reflects a deep-rooted understanding of both the harsh climatic conditions and the divine geometry required to house such potent cosmic forces.</p><p class='text-lg leading-relaxed font-light text-white/90 mb-6'>Visitors often report an unexplainable sense of calm and clarity upon entering these sacred precincts. This is not merely the effect of the thin, crisp mountain air, but the accumulated resonance of thousands of years of uninterrupted chanting, meditation, and devotion. The physical structures serve as a conduit between the earthly realm and the divine, acting as spiritual helmets that guard the valleys against natural calamities and spiritual entropy.</p><p class='text-lg leading-relaxed font-light text-white/90'>Engaging with this heritage demands a posture of humility and respect. By observing local customs, maintaining the sanctity of the environment, and approaching these shrines not just as tourist attractions but as living, breathing centers of cosmic energy, you participate in the ongoing cycle of preservation and reverence. The true essence of the Himalayas reveals itself only to those who listen with an open heart.</p></div>",
    keywords: ["Bijli Mahadev", "Kullu Valley", "Shiva temple", "Himalayan miracles"],
  },
  {
    title: "Hidimba Devi: The Demoness Turned Goddess",
    slug: "hidimba-devi-manali",
    metaDescription: "Delve into the story of Hidimba Devi, a character from the Mahabharata.",
    content: "<h2>From the Mahabharata to Manali</h2><p>Hidimba Devi's transformation is a powerful tale of redemption and devotion. Originally a Rakshasi, her marriage to Bhima and her subsequent penance led to her elevation as the chief deity of Manali.</p><h2>The Wooden Pagoda</h2><p>Her temple, a stunning multi-tiered wooden pagoda set among towering deodars, serves as a sanctuary. She wears the spiritual helmet of motherhood, protecting the region and serving as the focal point of the famous Kullu Dussehra festival.</p><div class='my-12 p-8 md:p-12 bg-gradient-to-br from-[#1a2e26] to-[#0d1713] text-white rounded-[2rem] shadow-2xl relative overflow-hidden group'><div class='absolute -top-20 -right-20 w-64 h-64 bg-terracotta/20 rounded-full blur-[80px] group-hover:scale-150 transition-transform duration-1000'></div><h3 class='text-2xl font-serif italic mb-4'>A Deeper Connection</h3><p class='text-lg leading-relaxed font-light text-white/90 mb-6'>The presence of these ancient deities transcends mere mythology; it is the very fabric that holds the spiritual and ecological balance of the Himalayas together. As you traverse these high-altitude paths, the silence of the mountains speaks volumes of the reverence the local communities hold for these protective energies. The architecture of the temples, intricately carved from the resilient Deodar cedar, reflects a deep-rooted understanding of both the harsh climatic conditions and the divine geometry required to house such potent cosmic forces.</p><p class='text-lg leading-relaxed font-light text-white/90 mb-6'>Visitors often report an unexplainable sense of calm and clarity upon entering these sacred precincts. This is not merely the effect of the thin, crisp mountain air, but the accumulated resonance of thousands of years of uninterrupted chanting, meditation, and devotion. The physical structures serve as a conduit between the earthly realm and the divine, acting as spiritual helmets that guard the valleys against natural calamities and spiritual entropy.</p><p class='text-lg leading-relaxed font-light text-white/90'>Engaging with this heritage demands a posture of humility and respect. By observing local customs, maintaining the sanctity of the environment, and approaching these shrines not just as tourist attractions but as living, breathing centers of cosmic energy, you participate in the ongoing cycle of preservation and reverence. The true essence of the Himalayas reveals itself only to those who listen with an open heart.</p></div>",
    keywords: ["Hidimba Devi", "Manali temple", "Mahabharata", "Himachal mythology"],
  }
];
`;
fs.writeFileSync(path, content);
